# SPDX-FileCopyrightText: 2023 Technology Innovation Institute (TII)
# SPDX-License-Identifier: Apache-2.0

keys:
  - &tervis age1ehmv0gg6xmj8nguakmj6tnhdhphjfnfwzpfshfupcrv67djn49hqzehl6y
  - &tervis-servu age10s55g3uvel6pwldnww2llf7dwhfka4xezv5lts73hhxv9r2xts5qt09dam
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *tervis
      - *tervis-servu
